name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**' # Chỉ chạy khi code trong thư mục frontend thay đổi
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      # Cách sử dụng VARIABLE
      env:
        VUE_APP_API_URL: ${{ vars.API_ENDPOINT }}
      run: npm run build
