name: Main Orchestration

on:
  workflow_dispatch: # Cho phép bấm nút chạy bằng tay trên web
  push:
    branches: [ "main" ]
    # Không có paths: nghĩa là thay đổi file nào cũng chạy (hoặc dùng để deploy production)

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Start
        run: echo "Starting main pipeline for deployment..."
      
      - name: Check Environment
        run: echo "Deploying to environment: ${{ vars.ENV_NAME }}"
